name:                dhall-typed
version:             0.1.0.0
github:              "mstksg/dhall-typed"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/dhall-typed#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -fobject-code
- -freduction-depth=1000
# - -Werror=incomplete-patterns

cpp-options:
- -DNOSING

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Dhall.Typed
  - Dhall.Typed.Core
  - Dhall.Typed.LC
  - Dhall.Typed.Plugin
  - Dhall.Typed.Type.Index
  - Dhall.Typed.Type.N
  - Dhall.Typed.Type.Bool
  - Dhall.Typed.Type.Option
  - Dhall.Typed.Type.Prod
  - Dhall.Typed.Type.Singletons
  - Dhall.Typed.Type.Singletons.TH
  dependencies:
  - containers
  - data-default
  - decidable
  - dhall
  - ghc
  - ghc-tcplugins-extra
  - mtl
  - profunctors
  - singletons
  - template-haskell
  - text
  - th-desugar

# executables:
#   dhall-typed-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - dhall-typed

# tests:
#   dhall-typed-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - dhall-typed
